[2019-01-13 23:09:50] INFO [run: run.py, 63] ================================== 测试开始 ==================================
[2019-01-13 23:09:50] INFO [log_case_info: case_log.py, 10] 测试用例：test_user_login_normal
[2019-01-13 23:09:50] INFO [log_case_info: case_log.py, 11] url：http://115.28.108.130:5000/api/user/login/
[2019-01-13 23:09:50] INFO [log_case_info: case_log.py, 12] 请求参数：{"name": "张三","password":"123456"}
[2019-01-13 23:09:50] INFO [log_case_info: case_log.py, 13] 期望结果：<h1>登录成功</h1>
[2019-01-13 23:09:50] INFO [log_case_info: case_log.py, 14] 实际结果：<h1>登录成功</h1>
[2019-01-13 23:09:50] INFO [log_case_info: case_log.py, 10] 测试用例：test_user_login_password_wrong
[2019-01-13 23:09:50] INFO [log_case_info: case_log.py, 11] url：http://115.28.108.130:5000/api/user/login/
[2019-01-13 23:09:50] INFO [log_case_info: case_log.py, 12] 请求参数：{"name": "张三","password":"1234567"}
[2019-01-13 23:09:50] INFO [log_case_info: case_log.py, 13] 期望结果：<h1>失败，用户名或密码错误</h1>
[2019-01-13 23:09:50] INFO [log_case_info: case_log.py, 14] 实际结果：<h1>失败，用户名或密码错误</h1>
[2019-01-13 23:09:51] INFO [log_case_info: case_log.py, 10] 测试用例：test_user_reg_exist
[2019-01-13 23:09:51] INFO [log_case_info: case_log.py, 11] url：http://115.28.108.130:5000/api/user/reg/
[2019-01-13 23:09:51] INFO [log_case_info: case_log.py, 12] 请求参数：{"name": "张三","password":"123456"}
[2019-01-13 23:09:51] INFO [log_case_info: case_log.py, 13] 期望结果：{"code": "100001", "data": {"name": "\u5f20\u4e09", "password": "e10adc3949ba59abbe56e057f20f883e"}, "msg": "\u5931\u8d25\uff0c\u7528\u6237\u5df2\u5b58\u5728"}
[2019-01-13 23:09:51] INFO [log_case_info: case_log.py, 14] 实际结果：{"code": "100001", "data": {"name": "张三", "password": "e10adc3949ba59abbe56e057f20f883e"}, "msg": "失败，用户已存在"}
[2019-01-13 23:09:51] INFO [log_case_info: case_log.py, 10] 测试用例：test_user_reg_normal
[2019-01-13 23:09:51] INFO [log_case_info: case_log.py, 11] url：http://115.28.108.130:5000/api/user/reg/
[2019-01-13 23:09:51] INFO [log_case_info: case_log.py, 12] 请求参数：{"name": "范冰冰","password":"123456"}
[2019-01-13 23:09:51] INFO [log_case_info: case_log.py, 13] 期望结果：{"code": "100000", "data": {"name": "\u8303\u51b0\u51b0", "password": "e10adc3949ba59abbe56e057f20f883e"}, "msg": "\u6210\u529f"}
[2019-01-13 23:09:51] INFO [log_case_info: case_log.py, 14] 实际结果：{"code": "100000", "data": {"name": "范冰冰", "password": "e10adc3949ba59abbe56e057f20f883e"}, "msg": "成功"}
[2019-01-13 23:09:52] INFO [run: run.py, 73] ================================== 测试结束 ==================================
